Triangle direction
Inat-qingbao/gaei_cpp pull request #28
Opened 2019-11-28 09:37 UTC by light-vr

Not tested yet.

2019-12-03 05:31 UTC, ouchiminh requested changes

2019-12-03 05:31 UTC, ouchiminh commented on gaei_cpp/triangle_direction.hpp
> +void triangle_direction_judege(std::vector<gaei::vertex<gaei::vec3f, gaei::color>>& vertexes, std::vector<std::array<int,3>>& as) {
点群を変更しないならば`const`参照にした方が良い
```suggestion
void triangle_direction_judege(const std::vector<gaei::vertex<gaei::vec3f, gaei::color>>& vertexes, std::vector<std::array<int,3>>& as) {
```

2019-12-03 05:38 UTC, ouchiminh requested changes

2019-12-03 05:38 UTC, ouchiminh commented on gaei_cpp/triangle_direction.hpp
> +void triangle_direction_judege(const std::vector<gaei::vertex<gaei::vec3f, gaei::color>>& vertexes, std::vector<std::array<int,3>>& as) {
ヘッダに関数の定義を書く場合はODRに違反しないようにinline関数にしてくれ
```suggestion
inline void triangle_direction_judege(const std::vector<gaei::vertex<gaei::vec3f, gaei::color>>& vertexes, std::vector<std::array<int,3>>& as) {
```

2019-12-07 11:10 UTC, ouchiminh requested changes

2019-12-07 11:10 UTC, ouchiminh commented on gaei_cpp/triangle_direction.hpp
> +        vbc.coord[2] = vertexes[as[i][2]].position.z() - vertexes[as[i][1]].position.z();
`gaei::vector<T,N>`は`operator-`をオーバーロードしているので、ベクトルの引き算ならば`vertexes[as[i][1]].position - vertexes[as[i][0]].position`のように書ける。

2019-12-07 11:10 UTC, ouchiminh commented on gaei_cpp/triangle_direction.hpp
> +    gaei::vector<double, 3> c, vab, vbc;
型をそろえてくれ
```suggestion
    gaei::vec3f c, vab, vbc;
```

2019-12-09 10:11 UTC, kongou923 approved these changes

2019-12-09 12:38 UTC, ouchiminh approved these changes

2019-12-09 12:39 UTC, merged