Wall#4
Inat-qingbao/gaei_cpp pull request #31
Opened 2019-12-07 13:51 UTC by light-vr

2019-12-07 14:18 UTC, ouchiminh requested changes
壁を構成する点の座標をみたらバグってそうだけど大丈夫か？

2019-12-07 14:18 UTC, ouchiminh commented on gaei_cpp/wall.hpp
> +    for (int i = 0; i < vertexes.size(); i++) {
無駄な比較と`signed`と`unsigned`の比較がある。
```suggestion
    for (unsigned i = 1; i < vertexes.size(); i++) {
```

2019-12-07 14:18 UTC, ouchiminh commented on gaei_cpp/wall.hpp
> +    vertexes.push_back({ {min_x,min_y,min_z},{} });
言うのを忘れていたが、これらの点と全く同じx-y座標を持つ点が全くないとは言い切れないのでmaxには1を足して、minには-1を足すようにして縮退が起こらないようにしてくれ。

2019-12-07 14:18 UTC, ouchiminh commented on gaei_cpp/wall.hpp
> +    long end = vertexes.size()-1;
-1必要か？

2019-12-07 14:18 UTC, ouchiminh commented on test/test_create_wall.cpp
> +    vertexes[2].position = gaei::vec3f{ {-3,0,3} };
xとyが全く同じ点があるというのは実際の状況と乖離している。

2019-12-09 09:29 UTC, kongou923 approved these changes

2019-12-09 10:02 UTC, ouchiminh requested changes

2019-12-09 10:02 UTC, ouchiminh commented on gaei_cpp/wall.hpp
> +        vertexes.push_back({ {vertexes[i].position.x(),vertexes[i].position.y(),min_z},{} });
min_zはただのx座標の差になっているので、この値をそのまま点のz座標とするのは問題がある。for文の前に最後に追加した点のz座標は与えられた点群の中で最も低い位置にあるので、そこからさらに引いてほしい。

2019-12-09 10:27 UTC, ouchiminh approved these changes

2019-12-09 10:27 UTC, merged