Vert to wrl#1
Inat-qingbao/gaei_cpp pull request #6
Opened 2019-10-04 13:48 UTC by light-vr

2019-10-04 14:06 UTC, Dustin-Tai approved these changes

2019-10-05 06:52 UTC, ouchiminh commented on gaei_cpp/vrml_writer.hpp
> +			out<<u8"#VRML V2.0 utf8\n;
騙したみたいになってて非常に申し訳ないんですが、ASCII文字はUTF-8でエンコーディングしてもShift-JISでエンコーディングしても全く同じバイト列になるので、多バイト文字を出力しない限り`u8`プレフィックスを付ける必要はないのです。

2019-10-05 07:08 UTC, ouchiminh requested changes

2019-10-05 07:08 UTC, ouchiminh commented on gaei_cpp/vrml_writer.hpp
> +		}
この辺はあとから絶対に修正が加わるので関数ではなくクラスにしたほうが良いかもなぁ.....

クラスが出来上がった後、どういう使い方をしたいか考えながら作ってもらえると嬉しい。できれば使うとき楽したい。

2019-10-08 04:55 UTC, ouchiminh approved these changes

2019-10-08 04:56 UTC, kongou923 approved these changes

2019-10-08 05:58 UTC, merged